/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */

export interface ChallengeOptionResponse {
  /** Challenge Progress Id */
  id: string;
  /** Challenge Answer */
  text: string;
  /** Challenge Option correct or not */
  correct: boolean;
  /** Image Source */
  imageSrc: string;
  /** Audio Source */
  audioSrc: string;
  /** Challenge Id */
  challengeId: string;
}
