/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Challenge Type (Select or Assist)
 */
export type ChallengeResponseType = typeof ChallengeResponseType[keyof typeof ChallengeResponseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChallengeResponseType = {
  SELECT: 'SELECT',
  ASSIST: 'ASSIST',
} as const;
