/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */

export interface ChallengeProgressResponse {
  /** Challenge Progress Id */
  id: string;
  /** Challenge Complete or Not? */
  completed: boolean;
  /** User Id */
  userId: string;
  /** Challenge Id */
  challengeId: string;
}
