/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */
import type { ChallengeResponseType } from './challengeResponseType';
import type { ChallengeProgressResponse } from './challengeProgressResponse';
import type { ChallengeOptionResponse } from './challengeOptionResponse';

export interface ChallengeResponse {
  /** Challenge Id */
  id: string;
  /** Challenge Question */
  question: string;
  /** Challenge Order */
  order: number;
  /** Challenge Type (Select or Assist) */
  type: ChallengeResponseType;
  /** Lesson Id */
  lessonId: string;
  /** Challenge Progress */
  challengeProgress?: ChallengeProgressResponse;
  /** Challenge Options */
  challengeOptions?: ChallengeOptionResponse[];
  /** Completed */
  completed: boolean;
}
