/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */

export interface CourseResponse {
  /** Course Id */
  id: string;
  /** Course Title */
  title: string;
  /** Image Source */
  imageSrc: string;
  /** Created At Unit */
  createdAt: string;
  /** Updated At Unit */
  updatedAt: string;
}
