/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateChallengeRequestType } from './createChallengeRequestType';

export interface CreateChallengeRequest {
  /** Challenge Question */
  question: string;
  /** Challenge Order */
  order: number;
  /** Type of Challenge */
  type: CreateChallengeRequestType;
  /** Lesson Id */
  lessonId: string;
}
