/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */

export interface GetCourseResponse {
  /** Course Id */
  id: string;
  /** Course Title */
  title: string;
  /** Course Image Source */
  imageSrc: string;
}
