/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */
import type { ChallengeResponse } from './challengeResponse';

export interface GetLessonResponse {
  /** Lesson Id */
  id: string;
  /** Lesson Title */
  title: string;
  /** Lesson Order */
  order: number;
  /** Challenges in Lesson */
  challenges: ChallengeResponse[];
  /** Completed or Not */
  completed: boolean;
}
