/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */
import type { SubscriptionResponse } from './subscriptionResponse';

export interface GetMeResponse {
  /** User ID */
  id: string;
  /** User full name */
  name: string;
  /** User email address */
  email: string;
  /** Whether auto-renewal is enabled */
  isAutoRenewal: boolean;
  subscription?: SubscriptionResponse;
  /** Source User Avatar */
  imageSrc: string;
}
