/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */
import type { GetCourseResponse } from './getCourseResponse';
import type { GetMeResponse } from './getMeResponse';

export interface GetUserProgressResponse {
  /** User Progress Id */
  id: string;
  /** Hearts left */
  hearts: number;
  /** Points in account */
  points: number;
  /** User Id */
  activeCourseId: string;
  /** Course information */
  activeCourse: GetCourseResponse;
  /** Active Course Id */
  userId: string;
  /** User information */
  user: GetMeResponse;
}
