/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */
import type { InitPaymentRequestBillingPeriod } from './initPaymentRequestBillingPeriod';
import type { InitPaymentRequestProvider } from './initPaymentRequestProvider';

export interface InitPaymentRequest {
  /** ID of the selected subscription plan */
  planId: string;
  /** Subscription billing period (monthly or yearly) */
  billingPeriod: InitPaymentRequestBillingPeriod;
  /** Payment provider */
  provider: InitPaymentRequestProvider;
}
