/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */

export interface LessonResponse {
  /** Lesson Id */
  id: string;
  /** Lesson Title */
  title: string;
  /** Lesson Order */
  order: number;
  /** Unit Id */
  unitId: string;
  /** Created At Unit */
  createdAt: string;
  /** Updated At Unit */
  updatedAt: string;
}
