/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */

export interface LoginRequest {
  /** Email address of the user */
  email: string;
  /** Password for the account */
  password: string;
}
