/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentDetailsResponseBillingPeriod } from './paymentDetailsResponseBillingPeriod';
import type { SubscriptionInfo } from './subscriptionInfo';

export interface PaymentDetailsResponse {
  /** Transaction ID */
  id: string;
  /** Billing period selected for the subscription */
  billingPeriod: PaymentDetailsResponseBillingPeriod;
  /** Subscription information including selected plan details */
  subscription: SubscriptionInfo;
}
