/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Transaction status
 */
export type PaymentHistoryResponseStatus = typeof PaymentHistoryResponseStatus[keyof typeof PaymentHistoryResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentHistoryResponseStatus = {
  PENDING: 'PENDING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
} as const;
