/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */
import type { PlanInfo } from './planInfo';

export interface SubscriptionInfo {
  /** Detailed information about the selected plan */
  plan: PlanInfo;
}
