/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateChallengeRequestType } from './updateChallengeRequestType';

export interface UpdateChallengeRequest {
  /** Challenge Question */
  question: string;
  /** Challenge Order */
  order: number;
  /** Type of Challenge */
  type: UpdateChallengeRequestType;
  /** Lesson Id */
  lessonId: string;
}
