/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateUnitRequest {
  /** Unit Title */
  title: string;
  /** Unit Description */
  description: string;
  /** Unit Order */
  order: number;
  /** Course Id */
  courseId: string;
}
