/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of Challenge
 */
export type UpdateChallengeRequestType = typeof UpdateChallengeRequestType[keyof typeof UpdateChallengeRequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateChallengeRequestType = {
  SELECT: 'SELECT',
  ASSIST: 'ASSIST',
} as const;
