/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateChallengeOptionRequest {
  /** Challenge Option Text */
  text: string;
  /** Challenge Option Correct? */
  correct: boolean;
  /** Challenge Option Image Source */
  imageSrc: string;
  /** Challenge Option Audio Source */
  audioSrc: string;
  /** Challenge Id */
  challengeId: string;
}
