/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateUserRequest {
  /** Name of the user */
  name: string;
  /** Email address of the user */
  email: string;
  /** Enable or disable two factor */
  isTwoFactorEnabled: boolean;
}
