/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Current subscription status
 */
export type UserSubscriptionResponseStatus = typeof UserSubscriptionResponseStatus[keyof typeof UserSubscriptionResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSubscriptionResponseStatus = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
} as const;
