/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Lingo API
 * OpenAPI spec version: 1.0.0
 */
import type { UserSubscriptionResponseStatus } from './userSubscriptionResponseStatus';

export interface UserSubscriptionResponse {
  /** Subscription ID */
  id: string;
  /** Current subscription status */
  status: UserSubscriptionResponseStatus;
  /** Subscription start date */
  startDate: string;
  /** Subscription end date */
  endDate: string;
  /** Stripe Subscription Id */
  stripeSubscriptionId?: string;
  /** Plan ID */
  planId: string;
  /** User ID */
  userId: string;
  /** Subscription Active Status */
  isActive: boolean;
}
